// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wznxmjugywmwwvnyomhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6bnhtanVneXdtd3d2bnlvbWhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTU5NDUsImV4cCI6MjA3MzU5MTk0NX0.Cu1dsQfvlUZ-Z3R4HNnVVTH74RQu-mgrIeIROB0lNnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});